# Generated by Django 4.1.5 on 2023-01-16 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divulgar', '0003_pet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='tag',
            new_name='tags',
        ),
    ]
