# Generated by Django 4.1.5 on 2023-01-16 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divulgar', '0004_rename_tag_pet_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('P', 'Para adoção'), ('A', 'Adoção')], default='P', max_length=1),
        ),
    ]
